### ISSUE TITLE
Feature Proposal: .zappaignore

### ISSUE THREAD

**Issue by kienpham2000** [Miserlou/Zappa#112]
I think it's easier to control files to ignore using this .zappaignore file (like .gitignore / .dockerignore) instead of "exclude" settings

**Comment by collingreen** [comment]
What makes it easier? Just that it is familiar because of git/docker?

At the moment, everything related to zappa is contained in a single place. This feels clean, although it doesn't actually have any specific value either.

Maybe a middleground would be the ability to specify an ignore file in addition to specifying the exclude list? This would allow not only the two options above, but a third (and, in my opinion much more valuable one) where you could specify a file (for example, your .gitignore file) AS your zappa ignore and keep the two in sync automatically. This wouldn't work for every use case, but when it did, that seems like the best case scenario.

**Comment by kienpham2000** [comment]
Hi @collingreen,

Using the .ignore file have several benefits:
1) most devs are pretty familiar with such file so it's not a new learning curve on how to ignore files
2) this file will make zappa_setting.json file much simpler because it's a seperation of concern and easier to support other simple regex
3) we don't have to duplicate ignore settings for each env like how the current json setting file is doing.

The specify your ignore file approach sounds good but I think to be able to support that, you have to support this default file anyway? 

But I think it's better for a cli / framework to be very opinionated, don't give users too much options, harder to manage the code for those features.

**Comment by Miserlou** [comment]
Closing, zappa_settings.json is essentially a .zappafile. Ignore is handled by `exclude` setting. I want to minimize the amount of [legacy](https://github.com/Miserlou/legacy) we introduce.
