### ISSUE TITLE
Question: Zappa vs "true" micro service architecture

### ISSUE THREAD

**Issue by fletort** [Miserlou/Zappa#1161]
This project is really great to can go with serverless infrastructure with an existing monolithic django.

But i would like to know if they are some difference with a true microservice architecture. 

I mean i will use zappa to put my monolithic application on a serverless infrastructure.

But maybe in parelle, il will wrote again some piece of code to get a true microservice architecture.

I think they are some better perfomance with a microservice arcitecture as the lambda instance will not raise all my monolothic django application but only what it need to do what it must do.... ? 
The difference is big ?

**Comment by Miserlou** [comment]
It's actually the opposite because of the keep-warms, but generally the main advantages of microservice architectures aren't performance based, they're really organizational.

The other primary advantage has nothing to do with architecture, which is out of project, scope, but rather the ability to build _event-driven_ applications which you can't do with traditional deployments.

Closing, generally Slack is a better place than GitHub for this type of question, which should be used for discussing features and code.
