### ISSUE TITLE
"message": "Endpoint request timed out"

### ISSUE THREAD

**Issue by Pronjaboy** [Miserlou/Zappa#1187]
Hello,

I am new to lambda, strill trying to figure it out

Followed the django zappa guide, create te project and deployed as dev. When I access the given url, I can see the expected 404 django error

https://7f7vxgidu1.execute-api.sa-east-1.amazonaws.com/dev/

I configured a postgres db, already on AWS RDS, with public access. And I have created a route /students that returns dummy data. Works fine on local, but when I update zappa an try to access https://7f7vxgidu1.execute-api.sa-east-1.amazonaws.com/dev/students/, I get a {
"message": "Endpoint request timed out"
}

Can someone help me to figure this out?

**Comment by Pronjaboy** [comment]
Figured it out. It was a problem with my VPC. Added 0.0.0.0/0 in my inbound rules for know, until I find a better solution.

**Comment by majinman** [comment]
@tiagocborg I am getting the same error message. Would you explain how to solve it?

**Comment by adam3039** [comment]
Also looking for a fix here as well. Adding "anywhere" like @tiagocborg did worked for me, but obviously this can't be good from a security perspective. My lambda function is pointed to the same VPC, so not sure what the fix is.

**Comment by guanidene** [comment]
This might help those who are others facing the same error but are not able to solve it.

I was facing the same 'Endpoint request timed out' issue, but for a very silly reason. After an entire day of debugging and almost giving up on Zappa / AWS Serverless, I found that my migrations did not apply fully while doing `zappa manage dev migrate`. The default 30 seconds timeout limit in the lambda function created by Zappa killed the migration process before its completion. I found this from cloudwatch logs (also visible via `zappa tail`). So turns out the timeouts were happening because my Django app would crash for almost every API call due to missing tables and no response was being returned.

This was somewhat difficult to catch me because some of my APIs were working (for which the migration was successful), and most of them were not.

So please make sure your migrations are fully applied if you are facing this issue. As a double-check, you can connect to the RDS cluster and ensure that the tables are actually created after the migration command is executed.
