### ISSUE TITLE
Can I use non-python dependencies? (MeCab)

### ISSUE THREAD

**Issue by evilplanet** [Miserlou/Zappa#1260]
I'm using a python package called [natto-py](https://github.com/buruzaemon/natto-py) which requires a non-python Japanese tokeniser called [MeCab](https://github.com/jordwest/mecab-docs-en) (C++). 

Is it possible to use this for my Zappa project? How can MeCab be installed on Lambda (since pip does not work)?

---------
Django 1.10 & Python 3.5

**Comment by cjh79** [comment]
If you can get the libraries into `/lib` within the .zip, they will be on LD_LIBRARY_PATH in the Lambda environment. I did this by putting them into `site-packages/lib` in my virtualenv. This is a kludgy way to go about it but I'm just trying to get something working for now. Maybe somebody more knowledgeable can suggest a better way.

**Comment by evilplanet** [comment]
@cjh79 Could you tell how to put it into `/lib` ? How to compile it into binary?

**Comment by cjh79** [comment]
You'll need to compile your MeCab library on an Amazon AMI EC2 instance and then copy the `.so` into your virtualenv. So the basic steps are:

1. Spin up an EC2 AMI instance (must be AMI, to match Lambda environment)
1. SSH in to the instance
1. Download and untar the MeCab `.tar.gz` file somewhere
1. Compile the library as described in MeCab's README
1. Copy the resulting compiled `.so` file somewhere safe (FTP or rsync it or something) 

Once you have the `.so` in your project area, copy it into your virtualenv under `lib/python*/site-packages/lib`. Now do your `zappa update` and the library should be found.

Of course, if you ever blow away your virtual env, you'll have to remember to re-copy the library there. You could ensure that by writing a wrapper script for `zappa update` that checks for that library before proceeding, otherwise you risk easily breaking your project.

This whole thing works because in Lambda,  `/var/task/lib` [is included](https://forums.aws.amazon.com/thread.jspa?messageID=706158) in `LD_LIBRARY_PATH`. `/var/task` is where your zappa project is unpacked and runs from, and `site-packages/*` is at the top level of the zappa package, which means your library ends up on `LD_LIBRARY_PATH`.

**Comment by scoates** [comment]
Looks like @cjh79 has this covered. Thanks!

Going to close this. Please reopen if there's something else that should be done in Zappa.
