### ISSUE TITLE
How to schedule a cloudwatch event as event source

### ISSUE THREAD

**Issue by rlaverde** [Miserlou/Zappa#1616]
I'm trying to schedule a lambda when a cloudwatch rule is triggered.

## Context

I'm using the following configuration, but I don't know which event should I capture, I haven't found any documentation neither in zappa or kappa

```
    "events": [
    {
        "function": "my_function.main",
        "event_source": {
          "arn":  "arn:aws:events:us-east-1:000000000000:rule/my-cloudwatch-rule",
        "events": {
              ""
        }
        }
      }
    ]
```

**Comment by rlaverde** [comment]
I implement a workaround sending the event to a SNS and listening the sns in the lambda event https://github.com/Miserlou/Zappa/blob/master/README.md#executing-in-response-to-aws-events

**Comment by ivanmartinvalle** [comment]
For anyone landing on here from Google (since I had this exact same issue): I reversed engineered how this works from [this PR](https://github.com/garnaat/kappa/pull/69/files) in Kappa. Some key notes:

- The CloudWatch rule will be auto-created for you. Only the name is extracted from the specified ARN. The ARN is also constructible by the name.
- The mappings from the "Kappa syntax" to the ["AWS API syntax" ](https://docs.aws.amazon.com/AmazonCloudWatchEvents/latest/APIReference/API_PutRule.html) exist in the `CloudWatchEventSource` implementation.
