### ISSUE TITLE
Cannot deploy with custom lambda_handler

### ISSUE THREAD

**Issue by aldwyn** [Miserlou/Zappa#1627]
## Context

I tried creating a custom handler that inherits `zappa.handler.LambdaHandler`. My app just works without the custom handler, but I need to add a custom S3 event, wherein whenever there is an S3 PUT, it will unzip the file and process the data. I just need to intercept/override the `handler` method and filter the records. But when deploy 

## Expected Behavior

The app should just successfully import the env settings while monitoring `zappa tail dev --since 5m`, and flag that the app is running.

## Actual Behavior

Raises this kind of error:
```
[1538127761180] module initialization error
Requested setting EXTENSIONS_MAX_UNIQUE_QUERY_ATTEMPTS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```
And after finding `EXTENSIONS_MAX_UNIQUE_QUERY_ATTEMPTS` on the entirety of my app, it was used on `django_extensions`, but I think the error is on creating the custom handler

## Possible Fix

Suggest an appropriate way to create a custom handler.

## Steps to Reproduce

1. Create a custom handler, and inherit `zappa.handler.LambdaHandler`.
2. Do deploy/update the app.
3. Check the error on `zappa tail`

## Your Environment

* Zappa version used: 0.46.2
* Operating System and Python version: macOS High Sierra
* The output of `pip freeze`:
* Link to your project (optional): Confidential
* Your `zappa_settings.py`: 
Ignore the `<mysite>` tags.
```json
{
    "dev2": {
        "aws_region": "us-east-1",
        "django_settings": "<mysite>.settings",
        "profile_name": "default",
        "project_name": "<mysite>-staging2",
        "exclude": [
            "static",
            "fabfile.py",
            "README.md",
            ".gitignore",
            "<mysite>-*",
            "zappa-env-*.json",
            "search-keywords.json",
            "requirements-ec2.txt",
            "lambda_packages",
            "boto3*",
            "botocore*",
            "*.sh",
            "*.log",
            "*.zip"
        ],
        "runtime": "python3.6",
        "s3_bucket": "<mysite>-dev2",
        "certificate_arn": "<scm-cert>",
        "domain": "alpha.api.<mysite>.com",
        "remote_env": "s3://<mysite>-api/zappa-env-settings-v2.json",
        "lambda_handler": "<mysite>.lambda_handler.handler",
        "timeout_seconds": 180
    }
```

**Comment by zsoobhan** [comment]
I came across the same issue and solved it for my use case by doing the following:
- instead of inheriting from `zappa.handler.LambdaHandler`, copy the  [file](https://github.com/Miserlou/Zappa/blob/master/zappa/handler.py) fully into the root of your project (make sure you have the correct version or just pull it out from your virtual env)
- rename the file to `custom_handler.py`
- in your zappa settings, add an entry `"lambda_function": "custom_handler.lambda_handler"`

You can now modify `custom_handler.lambda_handler` in the root of your project and add your custom s3 event e.g.
```python
def lambda_handler(event, context):  # pragma: no cover
    logger.info("======== CUSTOM HANDLER ========")
    # custom stuff goes here
    return LambdaHandler.lambda_handler(event, context)
```

Also, I had an issue with version `0.46.2` and had to downgrade to `0.45.1`. (https://github.com/Miserlou/Zappa/issues/1536)

I hope this helps.
