### ISSUE TITLE
Feature: Reserve concurrency

### ISSUE THREAD

**Issue by johnyoonh** [Miserlou/Zappa#1628]
Lambda has an option to set reserved concurrency. It would be nice to able to set this at the time of deployment by setting it in zappa_settings.json

**Comment by trenta3** [comment]
I agree. It would be especially useful for dev and staging environment where one can set it to a low limit to ensure that eventual bugs in the code do not start an extremely high number of lambda functions.

**Comment by M0dM** [comment]
Not sure, but this might be helpfull for you : 
https://github.com/Miserlou/Zappa/issues/1790

**Comment by trenta3** [comment]
@M0dM Can you please clarify why it would be helpful for this usecase?

This issue is about "reserved concurrency" which limits the maximum number of lambda instances that can be in concurrent execution for a specific lambda function, while the linked issue is about warm keeping at least a determined amount of lambdas.

**Comment by M0dM** [comment]
Oo sorry, this is definitely not the same idea, my bad...

**Comment by snowman2** [comment]
Related to #1445

**Comment by snowman2** [comment]
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lambda.html#Lambda.Client.put_function_concurrency

**Comment by snowman2** [comment]
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lambda.html#Lambda.Client.create_function

`PutFunctionConcurrency`

**Comment by snowman2** [comment]
Addressed in #1989
