### ISSUE TITLE
Dev and prod deployed to different projects in API gateway

### ISSUE THREAD

**Issue by evenv** [Miserlou/Zappa#189]
When deploying the same project to dev and prod, they are deployed as two different projects with names <projectname>-prod and <projectname>-dev in API GW, and as such they also get assigned different domains. I would expect them to be deployed as two stages of the same project, and as such be available as /dev and /prod on the same domain. Is this just me misunderstanding, or is there something that can be done to change this?

**Comment by Miserlou** [comment]
Yeah, that's correct, they're different 'projects', as you put it. This is by design. I want 'dev', 'staging' and 'prod' to all be in completely isolated environments and configurations so that there's never ever any chance of accidental data contamination. This also allows you to 'rollback' in a linear fashion.

Make sense?

**Comment by kienpham2000** [comment]
I like this design choice, even AWS suggest we use diff AWS account for prod and dev, not sure why they built API Gateway this way.

**Comment by evenv** [comment]
Thanks for the quick and clarifying response @Miserlou ! That makes sense. Although then I agree with @kienpham2000 that it's a mystery how AWS has built it this way. But then from what I've read there are several things about API GW that are less than clear. Anyway, thanks for a very interesting framework! Closing issue.

**Comment by Phonizx** [comment]
me now https://www.youtube.com/watch?v=E5qvz4cq3N8&t=29s&ab_channel=StratExsius
