### ISSUE TITLE
Error Status Codes are Injected into Response Body

### ISSUE THREAD

**Issue by dtenenba** [Miserlou/Zappa#190]
Given the following Flask App:

```python
from flask import Flask, request, abort, make_response
app = Flask(__name__)

@app.route('/')
def index():
    abort(make_response("my custom error", 500))

```

When I run this app locally and hit its endpoint, the output I see is:

    my custom error

When I deploy this app using zappa and hit its endpoint, the output I see is:

    500my custom error

What's going on? Different versions of Flask, perhaps?

**Comment by dtenenba** [comment]
I should note that 

    my custom error

is the expected/desired output.

**Comment by collingreen** [comment]
This is because of how the handler wraps content so it can be found by api gateway and translated into the correct response. This is the reason custom 404 pages also have the same issue (there is a <!DOCTYPE html>404 injected at the top).

This adds the content to your response:
https://github.com/Miserlou/Zappa/blob/master/zappa/handler.py#L195-L196

This matches the content:
https://github.com/Miserlou/Zappa/blob/master/zappa/zappa.py#L726-L740

This is a high priority for me, but I haven't nailed down exactly how I want it to go yet. Ideally we can strip the flag in API gateway before sending it on to the requester. If not, we'll have to get more clever about what is being added to the response that is both detectable by the api gateway regex and does not impede generating responses.

**Comment by Miserlou** [comment]
Yeah, you've stumbled onto Zappa's primary hack. If you can come up with a better solution, I'd love to hear it. API Gateway's capabilities may have improved to the point where this is no longer possible, but I don't know yet.

**Comment by randuhmm** [comment]
Hello All, I believe that I might have a possible solution for this. I believe that we can still leverage the lambda error string matching if we change the format of the error message. I suggest that, instead of using base 64 encoding on the entire error message string, we only base 64 encode the body and then URL encode the error message with the status. Thus a resulting error message from lambda may look like this:

`status=404&body=<base64 string>`

On the API Gateway, the Lambda Error Regex would now look like this:

`status=404.*`

Lastly, the Body Mapping Template would be:

    #set($message = $util.urlDecode($input.path('$.errorMessage')))
    $util.base64Decode($message.body)

The resulting payload would only contain the actual body without any need for the prefix:

`u"<!DOCTYPE html>" + unicode(response.status_code) + unicode('<meta charset="utf-8" />')`

I am going to run a quick test using this method and see if it will work. If so, I can apply the patch and submit a PR. Let me know if you have any thoughts. Thanks!

**Comment by Miserlou** [comment]
Very excited stuff - looking forward to hearing the results of your experiments!

**Comment by randuhmm** [comment]
To follow up, I was able to successfully remove the `<!DOCTYPE html>XXX` prefix from the response body, however I did so in a slightly different way than described above. I was having issues getting the `$util.urlDecode` function to unpack the string properly and getting access the properties directly. I decided to try using a JSON array to pass the status followed by the body as a base64 encoded string. Thus the python code to send the errorMessage looks something like this:

    errorMessage = json.dumps([
        unicode(response.status_code),
        base64.b64encode(response.data.encode('utf-8'))])

The Lambda Error Regex:

    \["400".*

The Body Mapping Template:

    #set($_body = $util.parseJson($input.path('$.errorMessage'))[1])
    $util.base64Decode($_body)

I will be submitting a PR very shortly, but be advised that this change actually causes some issues. There are many API Gateways already setup to use the legacy Regex and Body Mapping Templates. Introducing a new pattern will cause all the old ones to fail upon the next update of the Lambda Function. I might suggest using a flag to enable this new mapping so that we don't break existing deployments. Thoughts?

**Comment by collingreen** [comment]
Excited for this.

**Comment by Miserlou** [comment]
Nice, very much looking forward to this! I don't think $util.parseJson was available when I got started..

I don't mind requiring a redeployment as long as our version is < 1.0.0, but my mind can be swayed..

**Comment by Miserlou** [comment]
Any motion on that PR @randuhmm? :D

**Comment by fermuch** [comment]
just to confirm, do we need to make a redeploy? Is there an easy way to perform one?

**Comment by Miserlou** [comment]
For right now, until I come up with something better, yes. `zappa undeploy; zappa deploy`
