### ISSUE TITLE
Project still maintained/alive?

### ISSUE THREAD

**Issue by hkyq** [Miserlou/Zappa#1969]
Is the project still alive? Hundreds of open issues and commits are drying up.

**Comment by jmcvetta** [comment]
I suspect the issue here is that no one is paying for Zappa development.  The project's [Patreon page](https://www.patreon.com/zappa) has a modest goal of $3,000/mo - but only $68/mo in actual support.  

This is not a unique issue for Zappa.  All across the FOSS ecosystem, bit rot is setting in.  Because hundreds, if not thousands, of companies use the software to run their businesses - without contributing a dime to support development and maintenance.

Of course my company isn't contributing anything either.  We're also not (yet?!) using Zappa in production.  Even if I can convince my boss to kick in $50/mo, that's still not getting the project close to its (very modest) goal.

**Comment by hkyq** [comment]
Ah I didn't know Zappa had a Patreon. Perhaps @Miserlou could make a note at the top of the repo that development is stalled due to lack of funding? Assuming this is the case.

**Comment by chris-erickson** [comment]
Another possible avenue. https://github.com/sponsors

**Comment by rudyryk** [comment]
The project is definetelly woth being developed and supported. I'd set up monthly commitment of several bucks. How could we do that?

**Comment by rudyryk** [comment]
@jmcvetta As Open Source contributor by myself, I'd say that every penny and positive feedback matters. So I'd suggest to start small not nesessarily with $50-100. Thousands of peope are using Zappa I think. So It's not a problem to reach the goal even with micro payments with certain level of commitment. Just the matter of proper PR as I can see. Actually Zappa is looking great and it's not that obvious it needs some extra support.

**Comment by jneves** [comment]
Follow the link at the top of the README? https://www.patreon.com/zappaOn 15 Dec 2019 12:24, Alexey Kinev <notifications@github.com> wrote:The project is definetelly woth being developed and supported. I'd set up monthly commitment of several bucks. How could we do that?

**Comment by rudyryk** [comment]
Hello @jneves, I've edited my comment above and already set up monthly donation :)

**Comment by aralmpa** [comment]
Hi guys the link that @jneves shared regarding patreon funding leads to a 404 and I could not find any donation / support link at the **top** of the README - only at the **end** of the file leading to [this](https://www.patreon.com/zappa) which by the way does not give much flexibility to smaller payments.

The latter (small contributions) of course is a deeper issue as the other guys mentioned. Big companies use open source code without contributing and developers or professionals who use the package cannot afford or seem not to care to contribute especially if they see that their donation is a mere drop in the ocean. 

It would be nice if there were a lot of small donations (trully community funding).

**Comment by rudyryk** [comment]
Hello @aralmpa,

> much flexibility to smaller payments

What kind of smaller payments would you need? As I remember, there's an option to set up a custom amount but I don't know what is the minimum value.

**Comment by aralmpa** [comment]
Hello @rudyryk my point was more general. I mean there are 500 open issues and maybe I am wrong because I am really a newbie regarding open source projects but this tool seems to intrigue people and attract traffic.

I do not know if these people are professionals and they make direct profit from it but if a lot of users are freelance or low-wage developers maybe they could get convinced to throw in some money (5$, 7$ or 10$ / month) at least during the period at which they are using the library. 

Of course to see that the finance goal is 0.00001% fullfilled is really disheartening. Maybe the need for donation and support of the project could be more underlined in the README as well.

**Comment by lsorber** [comment]
The Zappa Patreon is 1.8% fulfilled. A long way to go, but it's something!

**Comment by flak153** [comment]
https://www.patreon.com/zappa

is the patreon. Does miserlou have any desire to come back to this project? He has not commited in a long time

**Comment by pagreene** [comment]
You can pay a custom amount when you select "become a patron". Patreon is in general a pretty awesome concept. I added my $3 to this project, as I used it almost daily. I honestly didn't even notice there was a Patreon available. Hopefully if enough people get on board, @Miserlou will be able to get back to active support.

That said, there is a fairly active Slack channel attached to this project as well: https://slack.zappa.io/, where you can get some support.

**Comment by degroat** [comment]
@pagreene That URL does not work, do you have the Slack URL handy?

**Comment by pagreene** [comment]
Perhaps this will work better: https://app.slack.com/client/T0NS4HCCR/C52L5BD4J?

**Comment by tbrlpld** [comment]
It's too bad that this project is not supported more. It is pretty amazing. 

Since this is driving a lot of business toward Amazon, it would be great if they give contribute to the project in some way. May that be maintenance or just financial support.

**Comment by jmcvetta** [comment]
I would guess that @Miserlou is busy running his [business](https://gun.io).  

You're right about Zappa driving a lot of business to AWS.  Though I think it would drive a lot _more_ business to AWS if it were actively developed.  Zappa is super cool.  But right now I can't recommend it to my clients for production use - precisely because it is not actively maintained.  If anything breaks on it they'd be shit out of luck.  

If Amazon wants to be super cool, the right thing to do is to hire Miserlou's company to maintain/improve Zappa.  I've heard Amazon quietly supports some other AWS-related FOSS projects.  Let's hope they decide to do the same for Zappa.  

Anyone here know the AWS product owner for Lambda?  Or spend enough with AWS that you have your own salesperson to speak with?  If so - talk to them and suggest that AWS support Zappa!

**Comment by tbrlpld** [comment]
I found this: https://github.com/aws/chalice

Looks like they are working on their own Python microframework, specifically aimed at „serverless“ hosting.

**Comment by synap5e** [comment]
Perhaps it would be possible for Zappa to be adopted by [Code Shelter](https://www.codeshelter.co/).
> Code Shelter is a collective of volunteer software developers that aims to help with maintaining popular open source projects whose authors need a hand or don't have the time to maintain them any more.

I feel like Zappa fits that bill perfectly with 10k+ stars and a community that is still reporting bugs and submitting PRs. It sounds like Code Shelter would allow the community to continue to develop Zappa, taking over in merging outstanding PRs since right now few PRs seem to get landed.

From the Code Shelter FAQs
> *What level of maintenance are you aiming for?*
> At the very least, we would like our memebrs to review/merge pull requests, fix critical bugs and make releases. Past that, the level of involvement is up to the maintainer(s) of each project, and obviously the more the better, but the explicit stated goal of Code Shelter is to allow popular projects to continue to live and evolve.

---

Personally I use Zappa extensively, but unless something changes I can see myself moving to (or at least trying out) serverless framework with [serverless-wsgi](https://github.com/logandk/serverless-wsgi).

**Comment by hkyq** [comment]
@synap5e that looks like a great option, probably our best. @Miserlou what do you think?

**Comment by jneves** [comment]
We're giving it a new attempt, me after sorting out some personal issues and other people just coming back onboard. 0.49.0 is out and I suspect 0.49.1 and 0.50 will follow pretty soon with some of the biggest blockers on my list removed. We're still sorting out the site FUBAR, sorry about that. The direct link to the slack is https://zappateam.slack.com (I've updated the README for now until we sort the rest).

On a more personal note, there's a reason why the project seemed abandoned in the last year. It had to do with the amount of times, after a full work week, I would open my laptop on a Saturday morning and read comments on issues with people complaining about what other people weren't doing for them for free. That sucked whatever energy I had to work on the project right out of me and ended up, for week after week for months, with me just closing the laptop and going to my family instead of working on this project. When I found myself in the same situation I started going through all the PRs, testing, proposing improvements, filtering and qualifying them. Because of that I got invited to be a core member and given permissions to do more work. So it's really hard for me to understand expectations without contribution. End of personal note.

**Comment by jneves** [comment]
Closing this for now. Might need to be reopened in the future.

**Comment by yassineim** [comment]
@jneves, as an extreme solution, you could always disable Issues but keep PRs. Still better than abandoning the project I guess

**Comment by jneves** [comment]
Nah, while the issues need a cleanup, they provide immediate feedback on issues. I suspect that about 200 of them have fixes already merged or that will be merged in the next release (as we're adding more debugging information and sort out the excludes issues). And I usually tend to screw something in a release, so that feedback is very welcome. Also, there's a bloody brilliant zappa community that answers to a lot of the issues well before any of the maintainers reach them, so we already have most issues filtered out by the time I get to them.

**Comment by aralmpa** [comment]
Sorry to post to a closed issue but did not want to make a new one for a related oncern / question of mine.

So I wanted to contribute some small amount to the project through the patreon page but without wanting to sound disrespectful or unelegant I noticed that the funding details in that page are really outdated (fund target seems really out of reach, and the name of the maintainer has not shown up in this repo since 2018 or so) so I would like to be sure that the money would reach the actual maintainers.

I guess the short-version is: will a contribution to the project's patreon page reach the current maintainers?

**Comment by techdragon** [comment]
@jneves I'd also like some clarification (like @aralmpa ) regarding the Patreon and where the money goes. Not implying malfeasance, I just want to make sure that the money I'm currently giving via Patreon, is getting to the actual project maintainer.

**Comment by dmellstrom** [comment]
Project moved to [zappa/Zappa](https://github.com/zappa/Zappa)

Many issues appear to have been transferred

@jneves 
Related question: OK with you if we migrate issues from here? I have a couple pet issues in my subscriptions that I feel are still worthy and open, but weren't transferred to the new repo -- maybe due to staleness, or maybe you are still working on that process?
