### ISSUE TITLE
Add ACME/Let's Encrypt Capability

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/Zappa#3]
This one would be huge. Not sure if it's possible, but a way to automatically have the SSL certificate update every month. Game changer.

**Comment by ScheerMT** [comment]
Hmm.. Not sure if this is relevant to Zappa's use case (Don't think cloudfront is included in this stack)..However, there is this [Guide](https://vittegleo.com/blog/letsencrypt-lambda-function/). Detailing how to renew an SSL certificate for CloudFront. 

Since lambda functions can be set on a cron schedule this seems like it is at least feasible to look into some more..

**Comment by Miserlou** [comment]
Ah, good lead! I think that ought to do it. Will investigate more.

**Comment by ScheerMT** [comment]
As far as implmenting and giving the option to users to enable this.... default on or default off? 

Best practice may be for a user to enable if they want it **but** in this case its so crucial to keep the certs updated that it might be better to default on...

**Comment by Miserlou** [comment]
Probably default off, as not everybody uses Let's Encrypt yet. For the time being, best to assume that people bring their own certs most of the time, although I look forward to a future where that's not the case. Also depends on how well this feature works!

**Comment by ScheerMT** [comment]
With that in mind I totally agree! Good job!

**Comment by Miserlou** [comment]
Hm, I don't think that the linked strategy will work out of the box, because that requires serving the response through CloudFront, which would be on a different subdomain. 

For Zappa, we'd have to set up a magic API Gateway path to serve the response. It's still doable, but a little bit tricker.

Do you want to try giving this a shot?

**Comment by berezovskyi** [comment]
AWS allows to generate free wildcard certificates using Certificate Manager and use them for Cloudfront distributions. Because API Gateway uses Cloudfront, I expect it to allow generating certs from Certificate Manager in future.

P.S. [AWS response](https://forums.aws.amazon.com/message.jspa?messageID=700392#700392):

> API Gateway currently doesn't support certificates from ACM, but we're working to get support. It's a high priority item on our backlog, but I don't have an ETA for you.

**Comment by Miserlou** [comment]
Oh, that's really interesting. Didn't know about that. Yes, that is something that we should support as well.

Although I don't think they are mutually exclusive. I would personally prefer Let's Encrypt for my projects, but I think it makes sense to support both.

Can ACM certs be generated programmatically? A major selling point of LE/ACME is that we can automatically generate new certificates, so we could have zero-configuration auto-renewing certs by using Lambda Scheduled Events.

**Comment by berezovskyi** [comment]
No idea about ACM API, but yes, ACME is a solid alternative.

**Comment by kevgliss** [comment]
ACM API only allows for Email verification atm, but I believe they are working on domain verification, which would allow programatic renewal. You could then leverage R53 to prove you own the domain in question. LE/ACME would work much the same way once they enable domain verification.

**Comment by Miserlou** [comment]
This is documented here: https://github.com/Miserlou/Zappa/blob/master/docs/domain_with_free_ssl.md
