### ISSUE TITLE
General deployment tool

### ISSUE THREAD

**Issue by ScheerMT** [Miserlou/Zappa#4]
Not sure if parts of this deployment tool could be pulled out to pull this off but here we go!

Could the general idea of deployment to lambda and setting up the API gateway be pulled out in order to generalize it enough to allow the language you deploy with not matter?

So each lambda function could be deployed in whatever language you choose and as long as it understands the template mappings you setup then the lambda endpoints to work with that setup.

If any of this doesn't make sense or isn't feasible let me know!

**Comment by Miserlou** [comment]
You mean to have a JS/Java version?

**Comment by ScheerMT** [comment]
kind of.. make this tool general enough so you can upload the lambda functions in whichever language AWS supports.

Each language will be able to make use of the standard way you are formatting requests and such making it easy for users to choose the language they like

**Comment by Miserlou** [comment]
Currently, Lambda only supports JavaScript, Java and Python.

I think the API gateway hacks would work for other platforms, but I don't know if there are equivalents of WSGI for Java/JS. 

Good idea, but closing this issue now because I'm not quite close enough to those communities to build anything useful for them right now.

**Comment by nueverest** [comment]
Lambda now supports C# .NET Core as well. 

Full list of languages supported: http://docs.aws.amazon.com/lambda/latest/dg/deployment-package-v2.html
