### ISSUE TITLE
Continuous Deployment with Zappa

### ISSUE THREAD

**Issue by aehlke** [Miserlou/Zappa#407]
We're continuously-deploying the services we're using Zappa for: on push to GitHub, our Jenkins 2 server gets pinged and once the test suite passes, the service gets automatically deployed to production.

This is slightly aspirational but we're close to having this set up. I'd like to document the pain points for potential followup work in Zappa.

The first one we've run into is that the Zappa command to deploy depends on whether the CloudFormation stack already exists - on initial deploy, it's `zappa deploy`, and then `zappa update` after that. Since `zappa deploy` gives exit code 0 whether or not it succeeded, and since its output is not machine-readable, we had to resort to something like this in our automation:

```
if zappa deploy | tee /dev/stderr | grep 'already deployed'; then
    zappa update
fi
```

... which is fragile and unintuitive. `zappa status` also gives exit code 0 whether or not the stack exists. The quick fix could be to return a non-zero exit code. Since Zappa configuration is descriptive, it could also be nicer to consolidate `deploy` and `update` into one command that "applies" the described service, much like you'd do with configuration management tools like Ansible.

I'd also be interested to hear about anyone else's experience with continuously-deploying Zappa services.

**Comment by Miserlou** [comment]
Nice, this is an excellent issue!

Changing the status codes would be trivial. Another option would be putting the `status` output in a machine readable format (ex with `--json`), so that you could simply parse it with `jq`.

Combining `deploy` and `update` is a different discussion, but much more feasible now that we are updating the API Gateway with CF stacks rather than boto API calls. [That being said, I'm actually not convinced that CF stacks are the way to go now that we have APIG configured to use Proxy+].

**Comment by aehlke** [comment]
Sounds like the status code change makes sense first, and then we can add e.g. `--json` on top of that without having to throw away any work.

Surprised to hear you're thinking to move away from CloudFormation - I don't know what Proxy+ is so I guess I'll dig into that. Since we've begun adopting CF via Troposphere, we're now moving everything in that direction since it makes so many operational needs simpler and safer. Happy to discuss this one more once I catch up on the context.

**Comment by Miserlou** [comment]
Previously we moved from boto to CF because the API Gateway templates were HUGE (~500Kb), but with a new API Gateway feature, they're down to <1.5kKb. More info here: https://blog.zappa.io/posts/unhacking-zappa-with-new-apigateway-features

Now it actually seems slower because you have to wait for the Stack to be created versus just directly making the API calls, and there are some issues with updating stacks across versions that'd be solved if we could just make the API calls directly.

Just spitballing here, would it be useful to you if Zappa just spit out the CF template rather than actually deployed it? Though a similar issue there is that Zappa only uses CF for the APIGW but not for the Lambda (by design).

Feel free to send a PR for the `status` status code issue.

**Comment by aehlke** [comment]
Thanks for the context!

There's a lot to unpack here so I'll defer deeper CloudFormation discussion for now on my end. I think the exit code + `--json` are the realistic next steps. Looking into adding them now.

**Comment by aehlke** [comment]
@Miserlou sorry, quick question: `dev` is behind `master`; your docs say:

> If dev falls behind master, feel free to rebase.

This would require a force push. What do you prefer here?

**Comment by Miserlou** [comment]
Yeah, keeping -dev as -dev seems to have been a pipe dream, just raw-dog it and submit to master..

**Comment by aehlke** [comment]
If you want to revisit that, I'd recommend setting up automation to push `master` to `dev` whenever it changes. I'd also suggest changing the GitHub default branch to `dev` if you want to follow the gitflow workflow.

**Comment by Miserlou** [comment]
Pushing master to dev would make sense, is there a service that does that or should I just set the up as a post-commit hook?

**Comment by aehlke** [comment]
I'm not sure if there's a service. You should be able to do it in a deployment hook in Travis CI though?

Gitflow might be heavier than you need for this - you could just rely on the "integration" branches off trunk for cutting and "baking" a release, and then tag those once released. Seems to be what some open source projects do rather than fully adopting gitflow but I don't have first-hand experience with this. (I think this would just be "GitHub Flow" - trunk + PR branches; I'm just unsure how you'd best handle tagging releases.)

**Comment by Miserlou** [comment]
I've been tagging published versions by putting in the commit message for the versions I publish to PyPI. Not the best but I find it easiest to manage.

The issue here is literally my own vanity. I like trying to "streak" on the activity grid on my profile section, and commits on non-master branches don't count towards that. I realize that that this means not having a best practice on our git branches, but I did the mental calculations and it's actually better for the health of the project for me to work on it more just to maintain my streak than it is to have a proper git flow. ¯\_(ツ)_/¯ sorry not sorry.

**Comment by aehlke** [comment]
Haha, totally understandable.

>commits on non-master branches don't count towards that

If you change the default branch for this project in GitHub to `dev`, it still doesn't?

**Comment by Miserlou** [comment]
Unfortunately not. Commits to forked projects don't count either, I don't know why. That one seems particularly ridiculous to me.

**Comment by aehlke** [comment]
One roadblock: currently, if you're running a command against several environments, it will fail in one environment and move on to the next. It's ambiguous how to translate this into exist codes. 2 options I can see:

A. Print the error and `sys.exit(1)` as soon as a command fails for any environment.
B. Print the error and note that at least one environment failed; move on to remaining environments; at end, `sys.exit(did_any_environment_fail)`

**Comment by Miserlou** [comment]
Are you talking about with `--all`? I literally just added that yesterday. Still tweaking.

Maybe `--all` shouldn't be used with a CI at all? IMO it seems it would be better to completely explicit, then only pass if _all_ of the environments pass.

**Comment by aehlke** [comment]
@Miserlou Yep, `--all`.

> Maybe --all shouldn't be used with a CI at all? 

Not sure what you mean by CI here?

**Comment by Miserlou** [comment]
CI/CD, whatever.

I definitively noticed that while putting in `--all`. At the time, I had a plan, but don't remember what it was. I think A is the right option - if something somewhere is failing, then something is probably boned somewhere and we shouldn't just try to power through it without first addressing that issue.

**Comment by aehlke** [comment]
Oh ok - yeah at least the way I'd interpret CI/CD with environments would be that the environment you ship to would depend on which branch changed: e.g. if `master`, ship the "production" environment; if `dev`, ship "staging".

Unless there's some use case of `--all` that I'm missing - perhaps multi-region deployments? (Production in both us-east-1 and us-west-1 for instance.)

**Comment by Miserlou** [comment]
I think this is taken care of now, please let me know if I've forgotten something.
