### ISSUE TITLE
Add Support for New Binary Data Api Gateway Features

### ISSUE THREAD

**Issue by Miserlou** [Miserlou/Zappa#481]
No more binary data hacks! Or, alternately, officially-supported binary data hacks.

Related:
https://aws.amazon.com/about-aws/whats-new/2016/11/binary-data-now-supported-by-api-gateway/
https://aws.amazon.com/blogs/compute/binary-support-for-api-integrations-with-amazon-api-gateway/
http://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings.html

**Comment by yoanisgil** [comment]
Would be a really nice feature to implement. I was looking to demo Django CMS using Zappa and there is no point in doing that if binary data is not supported.

**Comment by Miserlou** [comment]
Well, you can just upload to S3 directly. Honestly, you should probably be doing that anyway..

**Comment by yoanisgil** [comment]
That's indeed true but often times, people are stuck with frameworks which does things in a more traditional/legacy way. That's why I think supporting binary date might help filling in the gap.

I don't think that it's uncommon to have a Django model which uses an Image/File and that's also available via the Django admin. With API binary support and the 'storages' app users will be able to store media files in an S3 bucket (which is what they should probably be doing ;)).

**Comment by rogerhoward** [comment]
👍 
One of my projects would really benefit from this - I'm dynamically generating images. While it's not *hard* to push the results to S3, the problem is having to issue a redirect at that point - which means every call to this endpoint results in a redirect to another domain, something which not every client handles well.

Yes, for many purposes - serving static assets - pushing them to S3 is absolutely the right way. But, as Amazon itself has acknowledged by finally adding binary support in API Gateway - that doesn't fit every use case.

**Comment by kamilkp** [comment]
I have a service that converts text into pdf. So I need to return pdf binary data (application/pdf) from my lambda function. Any progress on that feature yet? I don't want to save temporary pdfs to S3 and serve them from there.

Or otherwise any ideas how to manually configure that in AWS?

**Comment by wobeng** [comment]
I submitted a pull request for binary support, which should allow you to generate images on the fly

#657

**Comment by Miserlou** [comment]
This has landed. Awesome.
