### ISSUE TITLE
Setting lambda env variables does not work.

### ISSUE THREAD

**Issue by horenmar** [Miserlou/Zappa#500]
I am testing zappa for deployment of event-driven lambda functions (no APIGW component) and ran into trouble with env variables. According to documentation, `zappa_settings.json` like this
```
 {
    "dev": {
    ...
    "environment_variables": {"NICE": "To", "SEE" : "You"},
    ...
    }
}
```
should set two environment variables for the lambda, `NICE` and `SEE`. However, the lambda does not have these environment variables set, as verified by both `print(os.environ)` and looking at the lambda in AWS management console. Adding an environment variable manually works.

**Comment by Miserlou** [comment]
I don't know what you mean by "Lambda does not have these environment variables set."

Zappa environment variables have existed long before "Lambda environment variables", which I think were only added last week. They're not the same thing, and I don't know how the two interact. Can somebody confirm this? Maybe your AWS environment variables are overriding the Zappa ones, but I don't see how that's possible. I think this more likely due to there being no APIGW than AWS Env, but needs investigation.

**Comment by horenmar** [comment]
I expected the `environment_variables` to be set as Lambda environment variables.

**Comment by Miserlou** [comment]
You mean the AWS ones?

**Comment by Miserlou** [comment]
If we do add support for those, it'll likely be done in a vendor prefixed way, ex `aws_environment_variables`

**Comment by Miserlou** [comment]
Cannot confirm yet, still investigating.

**Comment by Miserlou** [comment]
Confirmed it works with and without API Gateway, feel free to ask me to reopen if you can provide steps to reproduce.
