### ISSUE TITLE
Flask Support

### ISSUE THREAD

**Issue by Doerge** [Miserlou/Zappa#7]
Is there any roadmap for flask support?
And is there anything I can do to help?

**Comment by Miserlou** [comment]
There is no roadmap yet, I posted a request for assistance on the official Flask list, but didn't get any response.

Really the issue is that I'm a Django guy, not a Flask guy, so I don't know if I know how to write something that Flask people _want_. For instance, how do "management" commands work? Which version of Flask should I target? Etc etc etc.

Really most of the work needs to be done in the design of the interface. Actually it work should be quite easy, shouldn't take more than an afternoon.

Do you want to help? That'd be amazing.. even just some guidance on what the library would look like, how it should be used, etc, would go a long way.

**Comment by cariaso** [comment]
Count me in as well.

**Comment by Miserlou** [comment]
Great!

**Comment by Miserlou** [comment]
Okay, I've started a new project and added you as collaborators. I'm travelling today so won't be able to put anything in there, but feel free to start sketching.

I'm a massive proponent of README Driven Development, so please try creating a README file of what the project's usage would look like, then we can start to build the product based on that.

Sound good?

**Comment by Kisung** [comment]
That's sounds good...

**Comment by cariaso** [comment]
To make it easy to click instead of hunt, that project is at
https://github.com/Miserlou/flask-zappa

**Comment by Miserlou** [comment]
Flask now works right out of the box with the main Zappa client!

Thanks to @Doerge for all his hard work on this!
