### ISSUE TITLE
Documentation contains no warning against threads

### ISSUE THREAD

**Issue by texonidas** [Miserlou/Zappa#705]
As someone who has previously built a flask app, and is using Zappa to go serverless, I have spent the last two weeks bashing my head against a wall trying to determine why certain pieces of my application aren't working.

I have previously been sending batch emails by spinning up a thread per email and then posting it to my mail provider, as I need non-blocking requests. Nowhere in the documentation was it made clear that threads don't work as expected in lambda. Would definitely be worthwhile noting some "basics of serverless" for those of us with gappy knowledge.

**Comment by flux627** [comment]
Related: #603

Once implemented, you can use worker processes instead of threads to do this kind of async work.

**Comment by Miserlou** [comment]
I'm actually not sure what you mean. You should be able to spawn threads and long running processes on Lambda AFAIK.

**Comment by flux627** [comment]
That's technically true, with some critical caveats. If you need a non-blocking request (as @texonidas said) then that means he's returning a response to the user before his threads are finished. AWS calls these "background processes", and there are two important things to keep in mind:

1. Background processes *only* run while a function is executing. If your function finishes before background processes are finished, then they are "frozen" and then "thawed" again if the container is reused during another invocation.
2. Since containers are not guaranteed to be reused, you can't depend on those processes finishing.

This makes sense, as if you could spin up processes after a very short invocation time, you'd be effectively getting CPU cycles for free!

Sources:
https://aws.amazon.com/blogs/compute/container-reuse-in-lambda/
http://docs.aws.amazon.com/lambda/latest/dg/lambda-introduction.html

**Comment by texonidas** [comment]
Thanks @flux627! I was searching threads in issues, didn't even occur to me to try workers. Given that all I'm doing is a post request, I'm just sending it to SQS instead, and then consuming it from a periodic lambda call. Roughly what is described in the thread you linked actually hahaha.
