### ISSUE TITLE
Issue installing 0.41.1 on Windows

### ISSUE THREAD

**Issue by fifthecho** [Miserlou/Zappa#809]
## Context
When installing in Python 3.6 on Windows, install fails with:

```
Collecting zappa
  Using cached zappa-0.41.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "C:\Users\fifthecho\AppData\Local\Temp\pip-build-fp131vse\zappa\setup.py", line 7, in <module>
        from pypandoc import convert
    ModuleNotFoundError: No module named 'pypandoc'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\fifthecho\AppData\Local\Temp\pip-build-fp131vse\zappa\setup.py", line 10, in <module>
        README = open(os.path.join(os.path.dirname(__file__), 'README.md')).read()
      File "c:\python36\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 48630: character maps to <undefined>
```

## Your Environment

* Zappa version used: 0.41.1
* Operating System and Python version: Windows 10, Python 3.6.1

**Comment by Miserlou** [comment]
Ah fuck.

**Comment by fifthecho** [comment]
It's worth noting that Zappa 0.41.0 installs fine in Windows.

**Comment by Miserlou** [comment]
Works on OSX/Py2.7. 

I don't have a Windows machine, can you see what changed? Something in the README file that Windows doesn't like?

**Comment by gdw2** [comment]
I'm seeing this too.  I'll see what I can find.

**Comment by fifthecho** [comment]
https://github.com/Miserlou/Zappa/pull/811 should fix this. It's using pypandoc to download pandoc and make sure it's in place. Also, pypandoc wasn't in the requirements so that was causing the issues as well.

**Comment by gdw2** [comment]
For me, it seems that removing this line with the Japanese characters fixes the install:
https://github.com/Miserlou/Zappa/blame/master/README.md#L919

Not sure why this is appearing just now.

**Comment by selepo** [comment]
When trying to install Zappa on Windows, I get another traceback, but still pandoc that seems to be the problem: 

`Collecting zappa
  Using cached zappa-0.41.1.tar.gz
    Complete output from command python setup.py egg_info:
    See http://johnmacfarlane.net/pandoc/installing.html
    for installation options
    ---------------------------------------------------------------

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user1\AppData\Local\Temp\pip-build-n8hmbglr\zappa\setup.py", line 8, in <module>
        README = convert('README.md', 'rst')
      File "F:\bin\development\WinPython\python-3.6.1\lib\site-packages\pypandoc\__init__.py", line 69, in convert
        outputfile=outputfile, filters=filters)
      File "F:\bin\development\WinPython\python-3.6.1\lib\site-packages\pypandoc\__init__.py", line 260, in _convert_input
        _ensure_pandoc_path()
      File "F:\bin\development\WinPython\python-3.6.1\lib\site-packages\pypandoc\__init__.py", line 544, in _ensure_pandoc_path
        raise OSError("No pandoc was found: either install pandoc and add it\n"
    OSError: No pandoc was found: either install pandoc and add it
    to your PATH or or call pypandoc.download_pandoc(...) or
    install pypandoc wheels with included pandoc.`

**Comment by selepo** [comment]
I have the same issue...

Environment:
Windows 10 and Python 3.6.1.

**Comment by dazcode** [comment]
Hey Guys

The error happens because the Python2 code in this case is not fully compatible with Python3. Data and encoding is completely differently in Python3. If you want to run Python2 code on Python3 you must update the code to be in compliance with the new Python3 requirements. The fact that the code seems to work just fine (except on windows) is completely misleading. The 'real' issue here is that Python3 now requires you to explicitly specify the file encoding when opening the file. If you don't specify the encoding, it will use the current default system setting to open the file with. If the system encoding and the file encoding happen to be incompatible, then it produces an error in Python3. This is in contrast with Python2 which just goes ahead and makes a best effort to open and decode the file without having to specify the encoding type. So while the error here is windows https://en.wikipedia.org/wiki/Windows-1252 failing to decode a UTF8 value, this issue can happen on any system where there is a machine/file encoding mismatch.


Its really hard to avoid introducing bugs in Python 3 unless you study how it works and the differences between Python 2. A lot of things simply do not work as expected. This issue as explained by the Python devs:

https://ncoghlan-devs-python-notes.readthedocs.io/en/latest/python3/text_file_processing.html#what-changed-in-python-3

http://python-notes.curiousefficiency.org/en/latest/python3/text_file_processing.html

https://ncoghlan-devs-python-notes.readthedocs.io/en/latest/python3/questions_and_answers.html#why-was-python-3-made-incompatible-with-python-2


some examples of possible fixes:
http://python-future.org/compatible_idioms.html#file-io-with-open


I've submitted a pull request with an example fix https://github.com/Miserlou/Zappa/pull/820

-David

**Comment by Miserlou** [comment]
Should be fixed by PR.
